### ISSUE TITLE
Fix docker based test

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/relayer#13]
- [ ] Add conditions to tests:
  * [ ] Add additional balance checks [after each set of transactions](https://github.com/strangelove-ventures/relayer/blob/main/test/relayer_gaia_test.go#L68)
- [ ] Audit tests, document and ensure passing:
  * [ ] [TestGaiaToGaiaStreamingRelayer](https://github.com/strangelove-ventures/relayer/blob/main/test/relayer_gaia_test.go#L28)
  * [ ] [TestGaiaReuseIdentifiers](https://github.com/strangelove-ventures/relayer/blob/main/test/relayer_gaia_test.go#L111)
  * [ ] [TestGaiaMisbehaviourMonitoring](https://github.com/strangelove-ventures/relayer/blob/main/test/relayer_gaia_test.go#L176)
  * [ ] [TestAkashToGaiaStreamingRelayer](https://github.com/strangelove-ventures/relayer/blob/main/test/relayer_akash_test.go)

**Comment by faddat** [comment]
really may be a better idea to test the relayer live.

A synthetic test will never really show you the issues.

**Comment by faddat** [comment]
imo:

- put some low value keys in secrets
- import them
- run against rpcs we set up

this way we can maybe capture metrics at every code change.

tbh, my performance relaying so far has been stellar.

**Comment by jackzampolin** [comment]
The docker based testing is to ensure base level comparability. Ofc a live production environment is the only real test (latency, etc...) but the docker based tests have been critical for development.

**Comment by jtieri** [comment]
Closing this issue and opening a new issue in the `cosmos/relayer` repo found [here](https://github.com/cosmos/relayer/issues/546)
