### ISSUE TITLE
Lock contention when unmarshaling connection query

### ISSUE THREAD

**Issue by faddat** [strangelove-ventures/relayer#21]
rly q connection  cosmoshub-4 connection-339

seems to die on me.

**Comment by jackzampolin** [comment]
Thanks for the report. Prob something stupid

**Comment by jackzampolin** [comment]
so dug into this. We are hanging on the [`MarshalJSON` command in `relayer/contextual.go`](https://github.com/strangelove-ventures/relayer/blob/main/relayer/contextual.go#L25). Looks like some lock contention that is going to be tricky to track down.

**Comment by jackzampolin** [comment]
Ok so I found the cause here. https://github.com/strangelove-ventures/relayer/blob/main/relayer/contextual.go#L28 calls https://github.com/strangelove-ventures/relayer/blob/main/relayer/encoding.go#L148. This is leading me rethink and rework the codec code which is good.

**Comment by jackzampolin** [comment]
fixed by https://github.com/strangelove-ventures/relayer/pull/34
