### ISSUE TITLE
Make directory for canonical paths between major chains

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/relayer#22]
We should collect the canonical paths to <> from major chains into an easy to consume format for constructing relayer configuration:

```bash
interchain/
├── chains
│   ├── cosmoshub-4.json
│   └── osmosis-1.json
├── cosmoshub-4
│   └── hubosmo.json
├── osmo
└── osmosis-1
    ├── osmoakt.json
    ├── osmodvpn.json
    └── osmoregen.json
```

These files should contain the standard chain settings for the major chains and the canonical paths between them. Consider data from the following chains

- `osmosis-1`
    * [ ] `chain.json`
    * [ ] paths
- `cosmoshub-4`
    * [ ] `chain.json`
    * [ ] paths
- `akashnet-2`
    * [ ] `chain.json`
    * [ ] paths
- `crypto-Org-Chain-Mainnet-1`
    * [ ] `chain.json`
    * [ ] paths
- `sifchain-1`
    * [ ] `chain.json`
    * [ ] paths
- `irishub-1`
    * [ ] `chain.json`
    * [ ] paths
- `core-1`
    * [ ] `chain.json`
    * [ ] paths
- `sentinelhub-2`
    * [ ] `chain.json`
    * [ ] paths
- `regen-1`
    * [ ] `chain.json`
    * [ ] paths
- `iov-Mainnet-Ibc`
    * [ ] `chain.json`
    * [ ] paths

The command line user experience for this feature should be:
- As a user I want to relay across production IBC chains
- First I download the config files for the chains I want to work against and configure RPC endpoints and wallets for them
- Second I download the paths for the chains I have configured

**Comment by faddat** [comment]
Hey I'm not certain about this.

I think that it may make more sense to include all of this info in a default configuration file
