### ISSUE TITLE
Change `rly start` to a state based model

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/relayer#24]
Currently the main loop in the `rly start` command starts a websocket connection with both `src` and `dst` the proceeds to respond to events. We need to shift `rly` to a model where we are running `QueryUnrelayedPackets` and `RelayPackets` on a timed loop. This refactor should also eliminate the `type Strategy interface` which is now obsolete.

**Comment by jtieri** [comment]
This was addressed [here](https://github.com/cosmos/relayer/pull/534) so gonna close this out
