### ISSUE TITLE
Audit and update documentation to reflect new structure

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/relayer#27]
Documentation is now outdated and incorrect in pretty much all cases. Two major changes make up the primary differences:
- [ ] State based relaying will now be the only way `rly` operates https://github.com/strangelove-ventures/relayer/issues/24
- [ ] The on disk light client that used to be a key feature is now gone in favor of running against archive nodes.

**Comment by jtieri** [comment]
There are two open issues in the `cosmos/relayer` repo regarding documentation audit/updates.
[here](https://github.com/cosmos/relayer/issues/549)
[here](https://github.com/cosmos/relayer/issues/364)

Gonna close this issue in favor of these other issues as the cosmos repo becomes the de facto relayer repo
