### ISSUE TITLE
RPC URLs as an array

### ISSUE THREAD

**Issue by faddat** [strangelove-ventures/relayer#37]
I'd like to be able to give the config file an array of RPC urls because relaying can strain a node's capacity to continue to sync effectively and relay.  

A decent default setting would be round-robin eg:

* if 2 then 50/50
* if 3 then 33/33/33
* if 4 then 25/25/25/25

This should allow for further QoS improvements and better overall IBC UX.

**Comment by faddat** [comment]
This should not go in rly.  

We should instead document using go-between https://github.com/yyyar/gobetween

**Comment by boojamya** [comment]
Moved over to Cosmos repo. Closing here. 

https://github.com/cosmos/relayer/issues/552
