### ISSUE TITLE
Chokes when there are too many transactions

### ISSUE THREAD

**Issue by faddat** [strangelove-ventures/relayer#39]
I did like:

`hermes tx raw ft-transfer cosmoshub-4 osmosis-1 transfer channel-0 1000 -d uosmo -n 1000 -r cosmos1yeac5tgm4mqwl4fyrqp34s0gq5fy8ugxcj76vc -t 60`

rly

was like:

rly?

it said

"Error: more than one relay msg found in tx query"

I may try this from the gaia CLI instead, to see if rly reacts differently to this.

**Comment by boojamya** [comment]
Raw transaction commands have been removed in recent Relayer refactor. 
Please open issue in Cosmos Repo if this is still wanted. 
#rly?
Closing.
