### ISSUE TITLE
Timeout errors when attempting to relay acknowledgements 

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/relayer#47]
`rly tx relay-acknowledgements` seems to always hang and then eventually timeout with the following error:
```
Error: post failed: Post "https://osmosis-1.technofractal.com:443": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I tested this across multiple nodes and it seems @faddat has also experienced this

**Comment by boojamya** [comment]
Issue moved over to Cosmos repo. 
https://github.com/cosmos/relayer/issues/554

Closing.
