### ISSUE TITLE
Add support for new function in ibc-go v2 - NegotiateAppVersion

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/relayer#48]
ibc-go v2.0.0 will be released soon and a new function `NegotiateAppVersion` will be added to the app module interface

As per the migration document: 
```
This function should perform application version negotiation and return the negotiated version.   
If the version cannot be negotiated, an error should be returned. This function is only used on the client side.
```

Support for this will need to be added to the relayer

See:
[Migration Docs](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/ibc-migration-v100.md#relayers)
[PR](https://github.com/cosmos/ibc-go/pull/384)

**Comment by boojamya** [comment]
Moved over to Cosmos repo. 
https://github.com/cosmos/relayer/issues/555
Closing.
