### ISSUE TITLE
Put all queries behind a Provider interface

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/relayer#6]
This provider interface should have all the different queries that are needed by the relayer. First provider to implement will be called `ArchiveNodeProvider`. Other providers like `PostgresProvider` or `RedisProvider` should be implemented as other data stores become available. First thing to do here would be to catalogue which queries are implemented and used by the relayer and put them behind an interface

**Comment by jtieri** [comment]
Core relayer logic was moved behind the Provider interface in the `cosmos/relayer` [repo](https://github.com/cosmos/relayer/pull/521)
